apiVersion: apps/v1
kind: Deployment

metadata:
  name: best-practices-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo

  template:
    metadata:
      labels:
        app: demo
        enviroment: training
        tier: frontend

    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            
        ports:
        - containerPort: 80