# Source Code:
# https://github.com/dalita/devops-basics-with-dali

apiVersion: v1
kind: Pod

metadata:
  name: backend

spec:
  containers:
  - name: backend

    image: busybox

    command:
    - sh
    - -c
    - sleep 3600

    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: MYSQL_PASSWORD